### ISSUE TITLE
pip install --no-binary :all: -U python-datemath: FileNotFoundError: [Errno 2] No such file or directory: 'VERSION.txt'

### ISSUE THREAD

**Issue by bastbnl** [nickmaccarthy/python-datemath#12]
Hi,

I'm trying to update `python-datemath==1.4.6` to the latest version on Python 3.7.4 on Debian Linux using pip 19.3.1. The installation failed with this error:

```
    ERROR: Command errored out with exit status 1:
     command: /var/www/brownpapersession/dev/env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/tmp/pip-install-e1ovrmnq/python-datemath/setup.py'"'"'; __file__='"'"'/var/tmp/pip-install-e1ovrmnq/python-datemath/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /var/tmp/pip-install-e1ovrmnq/python-datemath/pip-egg-info
         cwd: /var/tmp/pip-install-e1ovrmnq/python-datemath/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/tmp/pip-install-e1ovrmnq/python-datemath/setup.py", line 19, in <module>
        with open('VERSION.txt', 'r') as f:
      File "/usr/local/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

I'll try to add logging later on if I can find any. The release on github at https://github.com/nickmaccarthy/python-datemath/archive/v1.4.9.zip does contain VERSION.txt .

**Comment by nickmaccarthy** [comment]
hey there @bastbnl , can you try the latest version, `1.4.9` and see if that fixes things for you?  That should contain `VERSION.txt` and should be compatible with python `3.7.4`

**Comment by bastbnl** [comment]
Just tried and nothing changed. Here's the command line I'm using:
```
(env) bastb@bastb-vps:/var/www/brownpapersession/dev/brownpapersession$ TMPDIR=/var/tmp pip install -U --no-binary :all: python-datemath
Collecting python-datemath
  Using cached https://files.pythonhosted.org/packages/b0/0d/2895cbda6ab60b4e7fd516b80957be7d856df4b81118f12e932fc65449e6/python-datemath-1.4.9.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /var/www/brownpapersession/dev/env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/tmp/pip-install-eeg3p7ed/python-datemath/setup.py'"'"'; __file__='"'"'/var/tmp/pip-install-eeg3p7ed/python-datemath/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /var/tmp/pip-install-eeg3p7ed/python-datemath/pip-egg-info
         cwd: /var/tmp/pip-install-eeg3p7ed/python-datemath/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/tmp/pip-install-eeg3p7ed/python-datemath/setup.py", line 19, in <module>
        with open('VERSION.txt', 'r') as f:
      File "/usr/local/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(env) bastb@bastb-vps:/var/www/brownpapersession/dev/brownpapersession$
```

**Comment by bastbnl** [comment]
Just tried installing using `TMPDIR=/var/tmp pip install -U --no-binary :all: python-datemath --no-clean`. The build directory still exists and `VERSION.txt` is actually missing:
```
(env) bastb@bastb-vps:/var/www/brownpapersession/dev/brownpapersession$ find /var/tmp/pip-install-g6cx8s8h/python-datemath/ -ls
   562484      4 drwxr-xr-x   5 bastb    bastb        4096 Oct 31 08:19 /var/tmp/pip-install-g6cx8s8h/python-datemath/
   562490      4 drwxr-xr-x   2 bastb    bastb        4096 Oct 31 08:19 /var/tmp/pip-install-g6cx8s8h/python-datemath/python_datemath.egg-info
   562493      4 -rw-r--r--   1 bastb    bastb           1 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/python_datemath.egg-info/dependency_links.txt
   562492      4 -rw-r--r--   1 bastb    bastb         263 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/python_datemath.egg-info/SOURCES.txt
   562491      4 -rw-r--r--   1 bastb    bastb         823 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/python_datemath.egg-info/PKG-INFO
   562494      4 -rw-r--r--   1 bastb    bastb          45 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/python_datemath.egg-info/requires.txt
   562495      4 -rw-r--r--   1 bastb    bastb           9 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/python_datemath.egg-info/top_level.txt
   562496      4 -rw-r--r--   1 bastb    bastb         110 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/setup.cfg
   562277      4 -rw-r--r--   1 bastb    bastb         185 Oct 31 08:19 /var/tmp/pip-install-g6cx8s8h/python-datemath/pip-delete-this-directory.txt
   562485      4 -rw-r--r--   1 bastb    bastb         823 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/PKG-INFO
   562487      4 drwxr-xr-x   2 bastb    bastb        4096 Oct 31 08:19 /var/tmp/pip-install-g6cx8s8h/python-datemath/datemath
   562488      4 -rw-r--r--   1 bastb    bastb         276 Oct 24 02:42 /var/tmp/pip-install-g6cx8s8h/python-datemath/datemath/__init__.py
   562489     12 -rw-r--r--   1 bastb    bastb        8661 Oct 28 04:19 /var/tmp/pip-install-g6cx8s8h/python-datemath/datemath/helpers.py
   562497      4 -rw-r--r--   1 bastb    bastb        3069 Oct 28 04:38 /var/tmp/pip-install-g6cx8s8h/python-datemath/setup.py
   562498      4 drwxr-xr-x   2 bastb    bastb        4096 Oct 31 08:19 /var/tmp/pip-install-g6cx8s8h/python-datemath/pip-egg-info
   562486      8 -rw-r--r--   1 bastb    bastb        5656 Oct 28 04:21 /var/tmp/pip-install-g6cx8s8h/python-datemath/README.md
```

**Comment by bastbnl** [comment]
But is `VERSION.txt` missing from the tar.gz? Well, it appears so:
```
(env) bastb@bastb-vps:~$ wget https://files.pythonhosted.org/packages/b0/0d/2895cbda6ab60b4e7fd516b80957be7d856df4b81118f12e932fc65449e6/python-datemath-1.4.9.tar.gz
--2019-10-31 08:25:11--  https://files.pythonhosted.org/packages/b0/0d/2895cbda6ab60b4e7fd516b80957be7d856df4b81118f12e932fc65449e6/python-datemath-1.4.9.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.37.63, 2a04:4e42:9::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.37.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6844 (6.7K) [binary/octet-stream]
Saving to: ‘python-datemath-1.4.9.tar.gz’

python-datemath-1.4.9.tar.g 100%[=========================================>]   6.68K  --.-KB/s    in 0s

2019-10-31 08:25:11 (36.1 MB/s) - ‘python-datemath-1.4.9.tar.gz’ saved [6844/6844]

(env) bastb@bastb-vps:~$ tar -tzvf python-datemath-1.4.9.tar.gz
drwxr-xr-x nmaccarthy/staff  0 2019-10-28 04:38 python-datemath-1.4.9/
-rw-r--r-- nmaccarthy/staff 823 2019-10-28 04:38 python-datemath-1.4.9/PKG-INFO
-rw-r--r-- nmaccarthy/staff 5656 2019-10-28 04:21 python-datemath-1.4.9/README.md
drwxr-xr-x nmaccarthy/staff    0 2019-10-28 04:38 python-datemath-1.4.9/datemath/
-rw-r--r-- nmaccarthy/staff  276 2019-10-24 02:42 python-datemath-1.4.9/datemath/__init__.py
-rw-r--r-- nmaccarthy/staff 8661 2019-10-28 04:19 python-datemath-1.4.9/datemath/helpers.py
drwxr-xr-x nmaccarthy/staff    0 2019-10-28 04:38 python-datemath-1.4.9/python_datemath.egg-info/
-rw-r--r-- nmaccarthy/staff  823 2019-10-28 04:38 python-datemath-1.4.9/python_datemath.egg-info/PKG-INFO
-rw-r--r-- nmaccarthy/staff  263 2019-10-28 04:38 python-datemath-1.4.9/python_datemath.egg-info/SOURCES.txt
-rw-r--r-- nmaccarthy/staff    1 2019-10-28 04:38 python-datemath-1.4.9/python_datemath.egg-info/dependency_links.txt
-rw-r--r-- nmaccarthy/staff   45 2019-10-28 04:38 python-datemath-1.4.9/python_datemath.egg-info/requires.txt
-rw-r--r-- nmaccarthy/staff    9 2019-10-28 04:38 python-datemath-1.4.9/python_datemath.egg-info/top_level.txt
-rw-r--r-- nmaccarthy/staff  110 2019-10-28 04:38 python-datemath-1.4.9/setup.cfg
-rw-r--r-- nmaccarthy/staff 3069 2019-10-28 04:38 python-datemath-1.4.9/setup.py
```
It's in the zip file found on :
```
(env) bastb@bastb-vps:~$ wget https://github.com/nickmaccarthy/python-datemath/archive/v1.4.9.zip
--2019-10-31 08:32:23--  https://github.com/nickmaccarthy/python-datemath/archive/v1.4.9.zip
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/nickmaccarthy/python-datemath/zip/v1.4.9 [following]
--2019-10-31 08:32:23--  https://codeload.github.com/nickmaccarthy/python-datemath/zip/v1.4.9
Resolving codeload.github.com (codeload.github.com)... 140.82.114.9
Connecting to codeload.github.com (codeload.github.com)|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘v1.4.9.zip’

v1.4.9.zip                      [ <=>                                      ]  17.34K  --.-KB/s    in 0.09s

2019-10-31 08:32:24 (185 KB/s) - ‘v1.4.9.zip’ saved [17758]

(env) bastb@bastb-vps:~$ unzip v1.4.9.zip
Archive:  v1.4.9.zip
9a415b7576b413c62f7682ddf8b80b8d2b5c76f1
   creating: python-datemath-1.4.9/
  inflating: python-datemath-1.4.9/.gitignore
  inflating: python-datemath-1.4.9/.travis.yml
  inflating: python-datemath-1.4.9/CHANGELOG.md
  inflating: python-datemath-1.4.9/LICENSE
  inflating: python-datemath-1.4.9/README.md
 extracting: python-datemath-1.4.9/VERSION.txt
  inflating: python-datemath-1.4.9/build.sh
   creating: python-datemath-1.4.9/datemath/
  inflating: python-datemath-1.4.9/datemath/__init__.py
  inflating: python-datemath-1.4.9/datemath/helpers.py
  inflating: python-datemath-1.4.9/requirements-2.txt
  inflating: python-datemath-1.4.9/requirements-3.txt
 extracting: python-datemath-1.4.9/setup.cfg
  inflating: python-datemath-1.4.9/setup.py
  inflating: python-datemath-1.4.9/tests-legacy.py
  inflating: python-datemath-1.4.9/tests.py
```
And the release tarball also has `VERSION.txt`: 
```
(env) bastb@bastb-vps:~$ wget https://github.com/nickmaccarthy/python-datemath/archive/v1.4.9.tar.gz
--2019-10-31 08:33:58--  https://github.com/nickmaccarthy/python-datemath/archive/v1.4.9.tar.gz
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/nickmaccarthy/python-datemath/tar.gz/v1.4.9 [following]
--2019-10-31 08:33:58--  https://codeload.github.com/nickmaccarthy/python-datemath/tar.gz/v1.4.9
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v1.4.9.tar.gz’

v1.4.9.tar.gz                   [ <=>                                      ]  13.03K  --.-KB/s    in 0.1s

2019-10-31 08:33:59 (132 KB/s) - ‘v1.4.9.tar.gz’ saved [13338]

(env) bastb@bastb-vps:~$ tar -tzvf v1.4.9.tar.gz
drwxrwxr-x root/root         0 2019-10-28 04:47 python-datemath-1.4.9/
-rw-rw-r-- root/root       191 2019-10-28 04:47 python-datemath-1.4.9/.gitignore
-rw-rw-r-- root/root       362 2019-10-28 04:47 python-datemath-1.4.9/.travis.yml
-rw-rw-r-- root/root      1945 2019-10-28 04:47 python-datemath-1.4.9/CHANGELOG.md
-rw-rw-r-- root/root     11357 2019-10-28 04:47 python-datemath-1.4.9/LICENSE
-rw-rw-r-- root/root      5656 2019-10-28 04:47 python-datemath-1.4.9/README.md
-rw-rw-r-- root/root         5 2019-10-28 04:47 python-datemath-1.4.9/VERSION.txt
-rwxrwxr-x root/root       448 2019-10-28 04:47 python-datemath-1.4.9/build.sh
drwxrwxr-x root/root         0 2019-10-28 04:47 python-datemath-1.4.9/datemath/
-rw-rw-r-- root/root       276 2019-10-28 04:47 python-datemath-1.4.9/datemath/__init__.py
-rw-rw-r-- root/root      8661 2019-10-28 04:47 python-datemath-1.4.9/datemath/helpers.py
-rw-rw-r-- root/root       245 2019-10-28 04:47 python-datemath-1.4.9/requirements-2.txt
-rw-rw-r-- root/root       407 2019-10-28 04:47 python-datemath-1.4.9/requirements-3.txt
-rw-rw-r-- root/root        69 2019-10-28 04:47 python-datemath-1.4.9/setup.cfg
-rw-rw-r-- root/root      3069 2019-10-28 04:47 python-datemath-1.4.9/setup.py
-rw-rw-r-- root/root      9676 2019-10-28 04:47 python-datemath-1.4.9/tests-legacy.py
-rw-rw-r-- root/root      9848 2019-10-28 04:47 python-datemath-1.4.9/tests.py
```

Also, the release link on https://pypi.org/project/python-datemath/ to https://github.com/nickmaccarthy/python-datemath/tarball/1.4.9 is broken. It expands to https://codeload.github.com/nickmaccarthy/python-datemath/legacy.tar.gz/1.4.9 which returns nothing but `404: Not Found`

@nickmaccarthy does it make sense? Maybe some changes in the way the build is distributed?

**Comment by nickmaccarthy** [comment]
hey @bastbnl , thanks for pointing this out.  I added a `MANIFEST.in` to the project get setup.py to account for things that are not `.py` files.  That seems to have fixed it.  v1.5.0 should contain the fix.  Can you try that version and let me know if that fixes this for you?

**Comment by bastbnl** [comment]
Tried, tested and verified. Thanks @nickmaccarthy
